name: "👤 Update Bio"
description: Update biographical information
title: "[BIO] Update Profile"
labels: ["bio"]
body:
  - type: markdown
    attributes:
      value: |
        ## Update Biographical Information
        This will update your profile information displayed on the homepage.
        
  - type: textarea
    id: content
    attributes:
      label: Bio Information
      description: Include YAML front matter with your details
      placeholder: |
        ---
        name: "Jahir Uddin"
        tagline: "Expanding Horizon"
        title: "Graduate Research Assistant"
        institution: "University of Nebraska Medical Center"
        email: "juddin@unmc.edu"
        profiles:
          - {name: "Google Scholar", url: "https://scholar.google.com/..."}
          - {name: "LinkedIn", url: "https://linkedin.com/in/..."}
          - {name: "GitHub", url: "https://github.com/jukomol"}
        photo: /assets/img/profile.jpg
        download_cv: /assets/cv/Jahir_Uddin_CV.pdf
        summary: |
          PhD student working on AI-enabled safety systems for agriculture and occupational health.
        ---
      value: |
        ---
        name: "Jahir Uddin"
        tagline: "Expanding Horizon"
        title: "Graduate Research Assistant"
        institution: "University of Nebraska Medical Center"
        email: "juddin@unmc.edu"
        profiles:
          - {name: "Google Scholar", url: "https://scholar.google.com/"}
          - {name: "LinkedIn", url: "https://linkedin.com/in/"}
          - {name: "GitHub", url: "https://github.com/jukomol"}
        photo: /assets/img/profile.jpg
        download_cv: /assets/cv/Jahir_Uddin_CV.pdf
        summary: |
          PhD student researching AI-driven environmental and occupational safety systems.
        ---
        
    validations:
      required: true
